### ISSUE TITLE
Master Branch Rename: Java Client

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notifications-java-client#21]
## User Story - Business Need

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** DevOps engineer    
**I want** to rename the `master` branch to `main` in this repository  
**So that** our branch naming aligns with industry standards and promotes inclusive terminology.

### Additional Info and Resources
- [GitHub guide on renaming the default branch](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch) <--- follow step there to rename on GitHub and have Evan or Kyle add the correct permissions to main for the group to be able to merge.
- Steps to rename the branch:
  1. Update local clones:
     ```sh
     git branch -m master main
     git fetch origin
     git branch -u origin/main main
     git remote set-head origin -a
     ```
  2. Update any Github Actions to use the `main` branch.
  3. Update documentation to reflect the branch name change.

## Acceptance Criteria
- [x] Post a heads up prior to this change in DSVA #vfs-change-announcements detailing what is changing and when so those using this pkg can ensure they are OK / ask questions
- [x] The `master` branch has been successfully renamed to `main` in this repository.
- [x] Make sure whoever renames the branch takes note of the branch protection rules before renaming the branch, because they are not the same after renaming it to main.
- [x] Github Actions have been updated to reference the `main` branch.
- [x] All documentation and code references to the `master` branch have been updated to `main`.
- [x] Team is notified in Slack to run the `Update local clones` directions from above.

## QA Considerations
~~- Ensure that all automated tests run successfully after the branch rename.~~ no tests avaialble
~~- Verify that the deployment pipeline still functions correctly with the new branch name.~~ not part of any pipeline
- Check that any links or references to the branch in the documentation are updated and correct.

## Potential Dependencies
- Coordination with other teams that might have dependencies on the `master` branch.

**Comment by k-macmillan** [comment]
I suspect none. Our clients use the [Package](https://github.com/orgs/department-of-veterans-affairs/packages?repo_name=notifications-java-client) we provide, and I am fairly certain it does not care about git.

**Comment by cris-oddball** [comment]
to my knowledge, there are no tests available for this client; removing the QA label from it since I have no way to validate it.

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notifications-java-client/21?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by k-macmillan** [comment]
Confirmed with VEText that they use the package, and repo primary branch name change will not affect them.
