### ISSUE TITLE
SPIKE: Determine Java Client Usage

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notifications-java-client#6]
## Issue
Maintaining the Java client is non-trivial for our team. Determine how many services are utilizing the Java client and determine if we should discontinue it.

## Checklist
- [ ] Services using the java client are documented per environment
- [ ] Decision documented

## Tips
- Check Staging and Prod for any that aren't live
- Check logs over 3 months in case some notifications aren't as frequent that are using this
- You can see the java client is being used in the logs

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notifications-java-client/6?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled

**Comment by k-macmillan** [comment]
Determined we must maintain this. Closing.
